version: '3.3'

services:

  zookeeper:
      image: confluentinc/cp-zookeeper:latest
      network_mode: host
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      extra_hosts:
        - "moby:127.0.0.1" 
  kafka:
      image: confluentinc/cp-kafka:latest
      network_mode: host
      depends_on:
        - zookeeper
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: localhost:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_CREATE_TOPICS: "PATIENT:1:1"
      extra_hosts:
        - "moby:127.0.0.1"


  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --smallfiles --logpath=/dev/null
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"
